import express from "express";
import User from "../models/User.js";

const router = express.Router();

const workerProfiles = [
  {
    name: "Ravi Kumar",
    category: "Driver",
    area: "Banjara Hills",
    time: "Full Time",
    wages: { min: 10000, max: 20000 },
    gender: "Male",
    experience: "4 years",
    rating: 4.5,
    jobsDone: 23,
    about: "Experienced driver, own vehicle, available full time.",
  },
  {
    name: "Sunita Devi",
    category: "House Help",
    area: "Banjara Hills",
    time: "Part Time - Mornings",
    wages: { min: 5000, max: 10000 },
    gender: "Female",
    experience: "6 years",
    rating: 4.7,
    jobsDone: 41,
    about: "Reliable house help for cleaning and daily chores.",
  },
  {
    name: "Imran Khan",
    category: "Cook",
    area: "Jubilee Hills",
    time: "Full Time",
    wages: { min: 12000, max: 18000 },
    gender: "Male",
    experience: "8 years",
    rating: 4.8,
    jobsDone: 56,
    about: "North Indian and Hyderabadi cuisine specialist.",
  },
  {
    name: "Lakshmi Reddy",
    category: "Cook",
    area: "Jubilee Hills",
    time: "Part Time - Evenings",
    wages: { min: 6000, max: 9000 },
    gender: "Female",
    experience: "5 years",
    rating: 4.3,
    jobsDone: 32,
    about: "Home-style Telugu cooking, available evenings.",
  },
  {
    name: "Arun Yadav",
    category: "Electrician",
    area: "Madhapur",
    time: "Flexible",
    wages: { min: 20000, max: 45000 },
    gender: "Male",
    experience: "10 years",
    rating: 4.6,
    jobsDone: 78,
    about: "Licensed electrician for residential and commercial work.",
  },
  {
    name: "Shabana Begum",
    category: "House Help",
    area: "Madhapur",
    time: "Full Time",
    wages: { min: 7000, max: 12000 },
    gender: "Female",
    experience: "3 years",
    rating: 4.2,
    jobsDone: 18,
    about: "Dedicated full-time house help with childcare experience.",
  },
  {
    name: "Mahesh Naik",
    category: "Plumber",
    area: "Gachibowli",
    time: "Flexible",
    wages: { min: 8000, max: 15000 },
    gender: "Male",
    experience: "7 years",
    rating: 4.4,
    jobsDone: 45,
    about: "Quick response plumber for leaks and installations.",
  },
  {
    name: "Pooja Sharma",
    category: "Security Guard",
    area: "Gachibowli",
    time: "Full Time",
    wages: { min: 3000, max: 6000 },
    gender: "Female",
    experience: "2 years",
    rating: 4.0,
    jobsDone: 12,
    about: "Trained security guard for apartments and offices.",
  },
  {
    name: "Karthik Goud",
    category: "Carpenter",
    area: "Hitech City",
    time: "Weekends Only",
    wages: { min: 25000, max: 50000 },
    gender: "Male",
    experience: "12 years",
    rating: 4.9,
    jobsDone: 92,
    about: "Custom furniture and woodwork specialist.",
  },
  {
    name: "Farida Sheikh",
    category: "Construction Labour",
    area: "Hitech City",
    time: "Full Time",
    wages: { min: 5000, max: 9000 },
    gender: "Female",
    experience: "4 years",
    rating: 4.1,
    jobsDone: 28,
    about: "Hardworking construction labour, available full time.",
  },
];

const employerProfiles = [
  {
    name: "Priya Sharma",
    category: "Driver",
    area: "Banjara Hills",
    time: "Full Time",
    wages: { min: 8000, max: 15000 },
    gender: "No Preference",
    membersRequired: "1",
    about: "Looking for a reliable full-time driver.",
  },
  {
    name: "Neha Verma",
    category: "House Help",
    area: "Banjara Hills",
    time: "Part Time - Mornings",
    wages: { min: 4000, max: 8000 },
    gender: "Female",
    membersRequired: "1",
    about: "Need morning house help for a 3BHK apartment.",
  },
  {
    name: "Suresh Reddy",
    category: "Cook",
    area: "Jubilee Hills",
    time: "Full Time",
    wages: { min: 10000, max: 18000 },
    gender: "No Preference",
    membersRequired: "1",
    about: "Family of four needs a full-time cook.",
  },
  {
    name: "Priya Nair",
    category: "Cook",
    area: "Jubilee Hills",
    time: "Part Time - Evenings",
    wages: { min: 5000, max: 10000 },
    gender: "Female",
    membersRequired: "1",
    about: "Evening cook needed for dinner prep only.",
  },
  {
    name: "Amit Agarwal",
    category: "Electrician",
    area: "Madhapur",
    time: "Flexible",
    wages: { min: 18000, max: 40000 },
    gender: "Male",
    membersRequired: "1",
    about: "Office renovation — need an experienced electrician.",
  },
  {
    name: "Meera Rao",
    category: "House Help",
    area: "Madhapur",
    time: "Full Time",
    wages: { min: 6000, max: 12000 },
    gender: "Female",
    membersRequired: "2-3",
    about: "Large home needs full-time house help team.",
  },
  {
    name: "Nitin Arora",
    category: "Plumber",
    area: "Gachibowli",
    time: "Flexible",
    wages: { min: 7000, max: 14000 },
    gender: "No Preference",
    membersRequired: "1",
    about: "Urgent plumbing work for new apartment.",
  },
  {
    name: "Divya Iyer",
    category: "Security Guard",
    area: "Gachibowli",
    time: "Full Time",
    wages: { min: 2500, max: 5500 },
    gender: "No Preference",
    membersRequired: "2-3",
    about: "Gated community needs security guards.",
  },
  {
    name: "Rahul Bansal",
    category: "Carpenter",
    area: "Hitech City",
    time: "Weekends Only",
    wages: { min: 20000, max: 45000 },
    gender: "Male",
    membersRequired: "1",
    about: "Custom wardrobe needed, weekend work preferred.",
  },
  {
    name: "Ananya Gupta",
    category: "Construction Labour",
    area: "Hitech City",
    time: "Full Time",
    wages: { min: 4500, max: 8500 },
    gender: "No Preference",
    membersRequired: "4-5",
    about: "Small renovation project, need a labour team.",
  },
];

router.post("/", async (req, res, next) => {
  try {
    if (process.env.NODE_ENV !== "development") {
      return res.status(403).json({
        message: "Seed route is allowed only in development",
      });
    }

    await User.deleteMany({});

    const workers = workerProfiles.map((profile, index) => ({
      phone: `90000000${String(index).padStart(2, "0")}`,
      role: "worker",
      name: profile.name,
      category: profile.category,
      location: { area: profile.area, city: "Hyderabad" },
      time: profile.time,
      wages: profile.wages,
      gender: profile.gender,
      languages: ["Telugu", "Hindi"],
      verified: index % 2 === 0,
      about: profile.about,
      experience: profile.experience,
      rating: profile.rating,
      jobsDone: profile.jobsDone,
      available: true,
    }));

    const employers = employerProfiles.map((profile, index) => ({
      phone: `98888000${String(index).padStart(2, "0")}`,
      role: "employer",
      name: profile.name,
      category: profile.category,
      requirement: `Looking for a ${profile.category.toLowerCase()}.`,
      location: { area: profile.area, city: "Hyderabad" },
      time: profile.time,
      wages: profile.wages,
      gender: profile.gender,
      membersRequired: profile.membersRequired,
      languages: ["English", "Telugu"],
      verified: index % 3 !== 0,
      about: profile.about,
      postedAgo: new Date(Date.now() - index * 86400000),
    }));

    const inserted = await User.insertMany([...workers, ...employers]);

    return res.status(201).json({
      insertedCount: inserted.length,
      message: "Seed data inserted successfully",
    });
  } catch (error) {
    return next(error);
  }
});

export default router;
